theme: jekyll-theme-minimal
title: 12304b MOBILIZED OET POSITIONS
description: This is a map of the 9th MSC USARPAC available postions. Scroll to zoom, click and drag to navigate the map. Hover over an icon to view job title, click to read description. Clicking a green numbered icon will zoom to reveal additional positions in one location.
logo: 81fa64cc-3849-47a5-b5af-e22684e4cf78.jpg
